using RosaDB.Library.Core;
using RosaDB.Library.Models;

namespace RosaDB.Library.Query.TokenParsers;

public static class TokensToColumnsParser
{
    /// <summary>
    /// Converts the tokens generated by the tokenizer to valid Column array as per SQL 92 standards
    /// </summary>
    /// <param name="columnTokens"></param>
    /// <returns>list of columns result</returns>
    public static Result<Column[]> TokensToColumns(string[] columnTokens)
    {
        if(columnTokens.Length == 0) return new Error(ErrorPrefixes.QueryParsingError, "No columns specified");
        
        var tokens = columnTokens.ToList();
        if(tokens[0] == "(") tokens.RemoveAt(0);
        if(tokens[^1] == ")") tokens.RemoveAt(tokens.Count - 1);

        List<List<string>> tokensPerColumn = [];
        List<string> currentColumn = [];
        foreach (var token in columnTokens)
        {
            if (token == ",")
            {
                tokensPerColumn.Add(currentColumn);
                currentColumn = [];
            }
            else currentColumn.Add(token);
        }
        tokensPerColumn.Add(currentColumn);

        List<Column> columns = [];
        foreach (var tokensInColumn in tokensPerColumn)
        {
            var columnResult = TokensToColumn(tokensInColumn.ToArray());
            if (columnResult.IsFailure) return columnResult.Error;
            columns.Add(columnResult.Value);
        }

        return columns.ToArray();
    }

    /// <summary>
    /// Converts the tokens generated by the tokenizer to valid Column as per SQL 92 standards
    /// </summary>
    /// <param name="columnTokens"></param>
    /// <returns>Column result</returns>
    public static Result<Column> TokensToColumn(string[] columnTokens)
    {
        if(columnTokens.Length <= 1) return new Error(ErrorPrefixes.QueryParsingError, "No column specified");
        string columnName = columnTokens[0];
        switch (columnTokens[1])
        {
            case "CHAR": return TokensToCHAR(columnName, columnTokens[1..]);
            default: return new Error(ErrorPrefixes.QueryParsingError, $"datatype {columnTokens[1]} is unkown");
        }
    }

    private static Result<Column> TokensToCHAR(string name, string[] tokens)
    {
        if (tokens[0] != "CHAR") return new CriticalError();
        if (tokens[1] != "(") return new Error(ErrorPrefixes.QueryParsingError, "No beginning '(' found for CHAR type");
        if (!int.TryParse(tokens[2], out int size)) return new Error(ErrorPrefixes.QueryParsingError, "Could not parse size for CHAR type");
        if (tokens[2] != ")") return new Error(ErrorPrefixes.QueryParsingError, "No end ')' found for CHAR type");

        return Column.Create(name, DataType.CHAR, new {size});
    }
}